version: '3.2'  # To use bind mount, it needs to indicate version more than
services:
  postgres:
    image: postgres
    ports:
      - "3306:3306"
    volumes:
      - app_postgre:/var/lib/postgresql/data 
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'admin-pass'
    restart: always
  app:
    build: .
    image: iliasbot_rails
    container_name: 'app'
    command: bundle exec rails s
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
    depends_on:
      - postgres
    restart: always

volumes:
  app_postgre:
    external: true