status:
  success: 'SUCCESS'
  internal_error: 'INTERNAL ERROR'
  database_error: 'DATABASE ERROR'
  api_callback_error: 'API CALLBACK ERROR'
  invalid_params: 'INVALID PARAMS ERROR'
  invalid_id: 'INVALID ID ERROR'

expression:
  normal: 'normal'
  happy: 'happy'
  angry: 'angry'
  confused: 'confused'
  suprised: 'surprised'
  
